# Generated by Django 4.2.5 on 2023-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='media/profilepic/')),
            ],
        ),
    ]
